// Русские слова для тэгов и разделов справочника AniList.
//
// ОТКУДА СЛОВА
// Список перенесён из dictionary.json старого скрипта: там он собран руками
// и обкатан годами показа, а свой перевод рядом с ним расходился бы в словах.
// Порядок оставлен алфавитным, как в словаре: так новая строка из скрипта
// видна на глаз и долагается в одно место.
//
// НЕЗНАКОМЫЙ ТЭГ ОСТАЁТСЯ СОБОЙ
// Справочник AniList растёт быстрее словаря, и на любой неизвестный ключ
// возвращается сам ключ: английское слово в чипе честнее пропуска.
//
// РАЗДЕЛЫ ПРИХОДЯТ ДЕФИСАМИ
// Сервер отдаёт категорию видом «Theme-Sci Fi-Mecha». Знакомые разделы
// переведены целиком, у незнакомого берётся последняя часть: в заголовке
// группы «Mecha» лучше, чем «Theme-Sci Fi-Mecha».

/** Разделы справочника. Ключи — как их отдаёт сервер, без причёсывания. */
const GROUP_WORDS: Readonly<Record<string, string>> = {
  'Cast-Main Cast': 'Главные герои',
  'Cast-Traits': 'Черты героев',
  Demographic: 'Аудитория',
  Setting: 'Место действия',
  'Setting-Scene': 'Место действия',
  'Setting-Time': 'Время действия',
  'Setting-Universe': 'Вселенная',
  'Sexual Content': 'Взрослое',
  Technical: 'Исполнение',
  'Theme-Action': 'Боевик',
  'Theme-Arts': 'Искусство',
  'Theme-Arts-Music': 'Музыка',
  'Theme-Comedy': 'Комедия',
  'Theme-Drama': 'Драма',
  'Theme-Fantasy': 'Фэнтези',
  'Theme-Game': 'Игры',
  'Theme-Game-Card & Board Game': 'Карты и настольные игры',
  'Theme-Game-Sport': 'Спорт',
  'Theme-Other': 'Прочее',
  'Theme-Other-Organisations': 'Организации',
  'Theme-Other-Vehicle': 'Транспорт',
  'Theme-Romance': 'Романтика',
  'Theme-Sci Fi': 'Фантастика',
  'Theme-Sci Fi-Mecha': 'Меха',
  'Theme-Slice of Life': 'Повседневность',
}

/** Слова тэгов. Ключ — имя тэга у AniList, оно же уходит в запрос отбора. */
const TAG_WORDS: Readonly<Record<string, string>> = {
  '4-koma': '4-кома',
  Achromatic: 'Ахроматичность',
  'Achronological Order': 'Нехронологический порядок',
  Acrobatics: 'Акробатика',
  Acting: 'Актёрское мастерство',
  Adoption: 'Усыновление',
  Advertisement: 'Реклама',
  Afterlife: 'Загробная жизнь',
  'Age Gap': 'Разница в возрасте',
  'Age Regression': 'Регрессия возраста',
  Agender: 'Агендерность',
  Agriculture: 'Сельское хозяйство',
  Airsoft: 'Страйкбол',
  Alchemy: 'Алхимия',
  Aliens: 'Пришельцы',
  'Alternate Universe': 'Альтернативная вселенная',
  'American Football': 'Американский футбол',
  Amnesia: 'Амнезия',
  Anachronism: 'Анахронизм',
  'Ancient China': 'Древний Китай',
  Angels: 'Ангелы',
  Animals: 'Животные',
  Anthology: 'Антология',
  Anthropomorphism: 'Антропоморфизм',
  'Anti-Hero': 'Антигерой',
  Archery: 'Стрельба из лука',
  Aromantic: 'Аромантичность',
  'Arranged Marriage': 'Брак по расчёту',
  'Artificial Intelligence': 'Искусственный интеллект',
  Asexual: 'Асексуальность',
  Assassins: 'Убийцы',
  Astronomy: 'Астрономия',
  Athletics: 'Атлетика',
  'Augmented Reality': 'Дополненная реальность',
  Autobiographical: 'Автобиографичность',
  Aviation: 'Авиация',
  Badminton: 'Бадминтон',
  Ballet: 'Балет',
  Band: 'Группа',
  Bar: 'Бар',
  Baseball: 'Бейсбол',
  Basketball: 'Баскетбол',
  'Battle Royale': 'Королевская битва',
  Biographical: 'Биографичность',
  Bisexual: 'Бисексуальность',
  Blackmail: 'Шантаж',
  'Board Game': 'Настольная игра',
  'Boarding School': 'Школа-интернат',
  'Body Horror': 'Боди-хоррор',
  'Body Image': 'Образ тела',
  'Body Swapping': 'Обмен телами',
  Bowling: 'Боулинг',
  Boxing: 'Бокс',
  "Boys' Love": 'Сёнэн-ай',
  Brainwashing: 'Промывка мозгов',
  Bullying: 'Травля',
  Butler: 'Дворецкий',
  Calligraphy: 'Каллиграфия',
  Camping: 'Кемпинг',
  Cannibalism: 'Каннибализм',
  'Card Battle': 'Карточные бои',
  Cars: 'Машины',
  Centaur: 'Кентавры',
  CGI: 'CGI',
  Cheerleading: 'Чирлидинг',
  Chibi: 'Чиби',
  Chimera: 'Химеры',
  Chuunibyou: 'Чунибё',
  Circus: 'Цирк',
  'Class Struggle': 'Классовая борьба',
  'Classic Literature': 'Классическая литература',
  'Classical Music': 'Классическая музыка',
  Clone: 'Клоны',
  Coastal: 'Прибрежье',
  Cohabitation: 'Сожительство',
  College: 'Колледж',
  'Coming of Age': 'Взросление',
  Conspiracy: 'Заговор',
  'Cosmic Horror': 'Космические ужасы',
  Cosplay: 'Косплей',
  Cowboys: 'Ковбои',
  'Creature Taming': 'Укрощение существ',
  Crime: 'Преступность',
  'Criminal Organization': 'Преступная организация',
  Crossdressing: 'Кроссдрессинг',
  Crossover: 'Кроссовер',
  Cult: 'Культ',
  Cultivation: 'Культивация',
  Curses: 'Проклятия',
  'Cute Boys Doing Cute Things': 'Милые парни делают милые вещи',
  'Cute Girls Doing Cute Things': 'Милые девушки делают милые вещи',
  Cyberpunk: 'Киберпанк',
  Cyborg: 'Киборги',
  Cycling: 'Велоспорт',
  Dancing: 'Танцы',
  'Death Game': 'Игра на выживание',
  Delinquents: 'Хулиганы',
  Demons: 'Демоны',
  Denpa: 'Дэнпа',
  Desert: 'Пустыня',
  Detective: 'Детектив',
  Dinosaurs: 'Динозавры',
  Disability: 'Инвалидность',
  'Dissociative Identities': 'Диссоциативное расстройство',
  Dragons: 'Драконы',
  Drawing: 'Рисование',
  Drugs: 'Наркотики',
  Dullahan: 'Дюллахан',
  Dungeon: 'Подземелье',
  Dystopian: 'Антиутопия',
  'E-Sports': 'Киберспорт',
  'Eco-Horror': 'Эко-хоррор',
  Economics: 'Экономика',
  Educational: 'Обучающее',
  'Elderly Protagonist': 'Пожилой герой',
  Elf: 'Эльфы',
  'Ensemble Cast': 'Ансамбль героев',
  Environmental: 'Окружающая среда',
  Episodic: 'Эпизодичность',
  'Ero Guro': 'Эрогуро',
  Espionage: 'Шпионаж',
  'Estranged Family': 'Разлучённая семья',
  Exorcism: 'Экзорцизм',
  Fairy: 'Феи',
  'Fairy Tale': 'Сказка',
  'Fake Relationship': 'Фиктивные отношения',
  'Family Life': 'Семейная жизнь',
  Fashion: 'Мода',
  'Female Harem': 'Гарем',
  'Female Protagonist': 'Героиня в центре',
  Femboy: 'Фембой',
  Fencing: 'Фехтование',
  Filmmaking: 'Кинопроизводство',
  Firefighters: 'Пожарные',
  Fishing: 'Рыбалка',
  Fitness: 'Фитнес',
  Flash: 'Flash-анимация',
  Food: 'Кулинария',
  Football: 'Футбол',
  Foreign: 'Иностранное',
  'Found Family': 'Обретённая семья',
  Fugitive: 'Беглец',
  'Full CGI': 'Полный CGI',
  'Full Color': 'Цветное',
  Gambling: 'Азартные игры',
  Gangs: 'Банды',
  Gekiga: 'Гекига',
  'Gender Bending': 'Смена пола',
  Ghost: 'Призраки',
  Go: 'Го',
  Goblin: 'Гоблины',
  Gods: 'Боги',
  Golf: 'Гольф',
  Gore: 'Жестокость',
  'Graduation Project': 'Дипломная работа',
  Guns: 'Огнестрельное оружие',
  Gyaru: 'Гяру',
  Handball: 'Гандбол',
  Henshin: 'Хеншин',
  Heterosexual: 'Гетеросексуальность',
  Hikikomori: 'Хикикомори',
  'Hip-hop Music': 'Хип-хоп',
  Historical: 'Историческое',
  Homeless: 'Бездомные',
  Horticulture: 'Садоводство',
  'Human Experimentation': 'Эксперименты над людьми',
  'Ice Skating': 'Фигурное катание',
  Idol: 'Идолы',
  'Indigenous Cultures': 'Коренные культуры',
  Inn: 'Гостиница',
  Isekai: 'Исекай',
  Iyashikei: 'Иясикэй',
  'Jazz Music': 'Джаз',
  Josei: 'Дзёсэй',
  Judo: 'Дзюдо',
  Kabuki: 'Кабуки',
  Kaiju: 'Кайдзю',
  Karuta: 'Карута',
  Kemonomimi: 'Кэмономими',
  Kids: 'Детское',
  'Kingdom Management': 'Управление королевством',
  Konbini: 'Конбини',
  Kuudere: 'Кудере',
  Lacrosse: 'Лакросс',
  'Language Barrier': 'Языковой барьер',
  'LGBTQ+ Themes': 'ЛГБТК+',
  'Long Strip': 'Длинная полоса',
  'Lost Civilization': 'Потерянная цивилизация',
  'Love Triangle': 'Любовный треугольник',
  Mafia: 'Мафия',
  Magic: 'Магия',
  Mahjong: 'Маджонг',
  Maids: 'Горничные',
  Makeup: 'Макияж',
  'Male Harem': 'Реверс-гарем',
  'Male Protagonist': 'Герой в центре',
  Manzai: 'Мандзай',
  Marriage: 'Брак',
  'Martial Arts': 'Боевые искусства',
  Matchmaking: 'Сватовство',
  Matriarchy: 'Матриархат',
  Medicine: 'Медицина',
  Medieval: 'Средневековье',
  'Memory Manipulation': 'Манипуляция памятью',
  Mermaid: 'Русалки',
  Meta: 'Мета',
  'Metal Music': 'Метал',
  Military: 'Военное',
  'Mixed Gender Harem': 'Смешанный гарем',
  'Mixed Media': 'Смешанные медиа',
  Modeling: 'Модельный бизнес',
  'Monster Boy': 'Мальчик-монстр',
  'Monster Girl': 'Девочка-монстр',
  Mopeds: 'Мопеды',
  Motorcycles: 'Мотоциклы',
  Mountaineering: 'Альпинизм',
  'Musical Theater': 'Мюзикл',
  Mythology: 'Мифология',
  'Natural Disaster': 'Стихийное бедствие',
  Necromancy: 'Некромантия',
  Nekomimi: 'Некомими',
  Ninja: 'Ниндзя',
  'No Dialogue': 'Без диалогов',
  Noir: 'Нуар',
  'Non-fiction': 'Нон-фикшн',
  Nudity: 'Нагота',
  Nun: 'Монахини',
  Office: 'Офис',
  'Office Lady': 'Офис-леди',
  Oiran: 'Ойран',
  'Ojou-sama': 'Одзё-сама',
  Orphan: 'Сироты',
  'Otaku Culture': 'Отаку',
  'Outdoor Activities': 'Активный отдых',
  Pandemic: 'Пандемия',
  Parenthood: 'Родительство',
  Parkour: 'Паркур',
  Parody: 'Пародия',
  Philosophy: 'Философия',
  Photography: 'Фотография',
  Pirates: 'Пираты',
  Poker: 'Покер',
  Police: 'Полиция',
  Politics: 'Политика',
  Polyamorous: 'Полиамория',
  'Post-Apocalyptic': 'Постапокалиптика',
  POV: 'От первого лица',
  Pregnancy: 'Беременность',
  'Primarily Adult Cast': 'В основном взрослые',
  'Primarily Animal Cast': 'В основном животные',
  'Primarily Child Cast': 'В основном дети',
  'Primarily Female Cast': 'В основном девушки',
  'Primarily Male Cast': 'В основном парни',
  'Primarily Teen Cast': 'В основном подростки',
  Prison: 'Тюрьма',
  'Proxy Battle': 'Битва через посредников',
  Psychosexual: 'Психосексуальное',
  Puppetry: 'Кукольный театр',
  Rakugo: 'Ракуго',
  'Real Robot': 'Реалистичные роботы',
  Rehabilitation: 'Реабилитация',
  Reincarnation: 'Реинкарнация',
  Religion: 'Религия',
  Rescue: 'Спасение',
  Restaurant: 'Ресторан',
  Revenge: 'Месть',
  'Reverse Isekai': 'Реверс-исекай',
  Robots: 'Роботы',
  'Rock Music': 'Рок',
  Rotoscoping: 'Ротоскопирование',
  'Royal Affairs': 'Королевские дела',
  Rugby: 'Регби',
  Rural: 'Сельская местность',
  Samurai: 'Самураи',
  Satire: 'Сатира',
  School: 'Школа',
  'School Club': 'Школьный клуб',
  'Scuba Diving': 'Дайвинг',
  Seinen: 'Сэйнэн',
  Shapeshifting: 'Смена облика',
  Ships: 'Корабли',
  Shogi: 'Сёги',
  Shoujo: 'Сёдзё',
  Shounen: 'Сёнэн',
  'Shrine Maiden': 'Мико',
  'Single-Page Chapter': 'Глава на одну страницу',
  Skateboarding: 'Скейтбординг',
  Skeleton: 'Скелеты',
  Slapstick: 'Буффонада',
  Slavery: 'Рабство',
  Snowscape: 'Снежные пейзажи',
  'Software Development': 'Разработка ПО',
  Space: 'Космос',
  'Space Opera': 'Космическая опера',
  Spearplay: 'Владение копьём',
  Steampunk: 'Стимпанк',
  'Stop Motion': 'Стоп-моушн',
  Succubus: 'Суккубы',
  Suicide: 'Самоубийство',
  Sumo: 'Сумо',
  'Super Power': 'Суперсила',
  'Super Robot': 'Супер-роботы',
  Superhero: 'Супергерои',
  Surfing: 'Сёрфинг',
  'Surreal Comedy': 'Сюрреалистическая комедия',
  Survival: 'Выживание',
  Swimming: 'Плавание',
  Swordplay: 'Владение мечом',
  'Table Tennis': 'Настольный теннис',
  Tanks: 'Танки',
  'Tanned Skin': 'Загорелая кожа',
  Teacher: 'Учитель',
  "Teens' Love": 'Тинс-лав',
  Tennis: 'Теннис',
  Terrorism: 'Терроризм',
  'Time Loop': 'Петля времени',
  'Time Manipulation': 'Манипуляция временем',
  'Time Skip': 'Таймскип',
  Tokusatsu: 'Токусацу',
  Tomboy: 'Томбой',
  Torture: 'Пытки',
  Tragedy: 'Трагедия',
  Trains: 'Поезда',
  Transgender: 'Трансгендерность',
  Travel: 'Путешествие',
  Triads: 'Триады',
  Tsundere: 'Цундере',
  Twins: 'Близнецы',
  'Unrequited Love': 'Неразделённая любовь',
  Urban: 'Городское',
  'Urban Fantasy': 'Городское фэнтези',
  Vampire: 'Вампиры',
  'Vertical Video': 'Вертикальное видео',
  Veterinarian: 'Ветеринар',
  'Video Games': 'Видеоигры',
  Vikings: 'Викинги',
  Villainess: 'Злодейка',
  'Virtual World': 'Виртуальный мир',
  'Visual Novel': 'Визуальная новелла',
  'Vocal Synth': 'Вокалоиды',
  Volleyball: 'Волейбол',
  VTuber: 'Витуберы',
  War: 'Война',
  Werewolf: 'Оборотни',
  Wilderness: 'Дикая природа',
  Witch: 'Ведьмы',
  Work: 'Работа',
  Wrestling: 'Рестлинг',
  Writing: 'Писательство',
  Wuxia: 'Уся',
  Yakuza: 'Якудза',
  Yandere: 'Яндере',
  Youkai: 'Ёкай',
  Yuri: 'Юри',
  Zombie: 'Зомби',

  // Взрослое: раздел «Sexual Content» справочника. В меню отбора эти тэги
  // видны только при разрешённом показе взрослого, но слова нужны всегда:
  // тэг может лежать в отборе с прежних настроек.
  Ahegao: 'Ахегао',
  Amputation: 'Ампутация',
  'Anal Sex': 'Анальный секс',
  Armpits: 'Подмышки',
  Ashikoki: 'Асикоки',
  Asphyxiation: 'Асфиксия',
  Bondage: 'Бондаж',
  Boobjob: 'Паизури',
  'Cervix Penetration': 'Проникновение в матку',
  Cheating: 'Измена',
  Cumflation: 'Камфлейшн',
  Cunnilingus: 'Куннилингус',
  Deepthroat: 'Глубокий минет',
  Defloration: 'Дефлорация',
  DILF: 'ДИЛФ',
  'Double Penetration': 'Двойное проникновение',
  'Erotic Piercings': 'Эротический пирсинг',
  Exhibitionism: 'Эксгибиционизм',
  Facial: 'Фейшиал',
  Feet: 'Ступни',
  Fellatio: 'Феллацио',
  Femdom: 'Фемдом',
  Fingering: 'Фингеринг',
  Fisting: 'Фистинг',
  'Flat Chest': 'Плоская грудь',
  Futanari: 'Футанари',
  'Group Sex': 'Групповой секс',
  'Hair Pulling': 'Таскание за волосы',
  Handjob: 'Хендджоб',
  'Human Pet': 'Человек-питомец',
  Hypersexuality: 'Гиперсексуальность',
  Incest: 'Инцест',
  Inseki: 'Инсеки',
  Irrumatio: 'Иррумация',
  Lactation: 'Лактация',
  'Large Breasts': 'Большая грудь',
  'Male Pregnancy': 'Мужская беременность',
  Masochism: 'Мазохизм',
  Masturbation: 'Мастурбация',
  'Mating Press': 'Мейтинг-пресс',
  MILF: 'МИЛФ',
  Nakadashi: 'Накадаши',
  Netorare: 'Нетораре',
  Netorase: 'Неторасе',
  Netori: 'Нетори',
  Oyakodon: 'Оякодон',
  'Pet Play': 'Пет-плей',
  Prostitution: 'Проституция',
  'Public Sex': 'Секс в общественном месте',
  Rape: 'Изнасилование',
  Rimjob: 'Римминг',
  Sadism: 'Садизм',
  Scat: 'Скат',
  Scissoring: 'Ножницы',
  'Sex Toys': 'Секс-игрушки',
  Shimaidon: 'Шимайдон',
  Squirting: 'Сквирт',
  Sumata: 'Сумата',
  Swapping: 'Обмен партнёрами',
  Sweat: 'Пот',
  Tentacles: 'Тентакли',
  Threesome: 'Тройничок',
  Virginity: 'Девственность',
  Vore: 'Воре',
  Voyeur: 'Вуайеризм',
  Watersports: 'Водные игры',
  Zoophilia: 'Зоофилия',
}

/** Слово из справочника или сам ключ: пробел в чипе хуже английского слова. */
function word(dict: Readonly<Record<string, string>>, key: string): string {
  return dict[key] ?? key
}

/** Русское слово тэга. */
export function tagWord(name: string): string {
  return word(TAG_WORDS, name)
}

/**
 * Русское слово раздела справочника. У незнакомого раздела берётся
 * последняя часть: сервер складывает вложенность дефисами, и хвост всегда
 * осмысленнее целого ключа.
 */
export function tagGroupWord(category: string): string {
  const known = GROUP_WORDS[category]
  if (known !== undefined) return known

  const tail = category.split('-').pop()
  return tail !== undefined && tail !== '' ? tail : category
}
